### PR TITLE
ping database with python instead of mysql client

### LINKED ISSUE #725: Use sqlalchemy Python script to test availability of database.
**Environment**:

  - CTFd Version/Commit:

2.0.0 branch

  - Operating System:

MacOS X, but building/deploying container images.

  - Web Browser and Version:

N/A

**What happened?**

The check using ``mysqladmin`` in ``docker-entrypoint.sh`` will fail if the target system only has MySQL libs package and doesn't have MySQL clients package.

Further, the wiki says:

> My personal suggestion is MySQL or MariaDB, but PostgreSQL will work just fine.

The ``docker-entrypoint.sh`` script is hard wired to MySQL and expects MySQL clients package to be installed. Would be nice that if also want to use PostgreSQL and only provide alternate ``Dockerfile`` and not change anything else, that this would work and didn't have to rewrite it. Similarly, if use alternate build system like S2I for OpenShift, that can reuse existing scripts unchanged.

**What did you expect to happen?**

Would hope database check is database agnostic and work with only database libs available.

**How to reproduce your issue**

In my case hit it as building from source using S2I (Source-to-Image) builder in OpenShift. The Python base images do not include MySQL clients package.

**Any associated stack traces or error logs**

```
Waiting for ctfd-mariadb to be ready
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
  | /opt/app-root/src/docker-entrypoint.sh: line 33: mysqladmin: command not found
 ...
```

**Solution**

Suggest database agnostic check be used which uses small Python script and ``sqlalchemy``.

```
import os
from sqlalchemy import create_engine
database = create_engine(os.getenv('DATABASE_URL'))
database.execute('select 1')
```

This has added benefit that also checks that required Python packages installed correctly and work before starting up the application.

It should also technically work for SQLite if someone wanted to override ``DATABASE_URL`` and use SQLite with file system path, to directory in a mounted persistent volume, rather than have database created in default location of source code directories where not possible to mounted a persistent volume. Although in SQLite case the database file would technically need to exist first.

### PR DESCRIPTION
**Pull request by frankli0324**
* Replaces `mysqladmin ping` with a custom script
* Closes #725

### CODE REVIEW

**Comment by frankli0324** [comment]
¿¿¿

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -6,35 +6,11 @@ WORKER_CLASS=${WORKER_CLASS:-gevent}
...
 
-# Check that a .ctfd_secret_key file or SECRET_KEY envvar is set
-if [ ! -f .ctfd_secret_key ] && [ -z "$SECRET_KEY" ]; then
-    if [ $WORKERS -gt 1 ]; then
-        echo "[ ERROR ] You are configured to use more than 1 worker."
-        echo "[ ERROR ] To do this, you must define the SECRET_KEY environment variable or create a .ctfd_secret_key file."
-        echo "[ ERROR ] Exiting..."
-        exit 1
-    fi
-fi
```
Comment (ColdHeat) [inline docker-entrypoint.sh:20]: I think it's a bad idea to remove this. You're right that the script doesn't consider if config.ini is hard coded but I think with a Docker container the better solution would be to use environment variables anyway.

File: ping.py [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+import time
+
+from sqlalchemy import create_engine
+from sqlalchemy.engine.url import make_url
+
+from CTFd.config import Config
+
+url = make_url(Config.DATABASE_URL)
+if not url.drivername.startswith("mysql"):
+    exit(0)
```
Comment (ColdHeat) [inline ping.py:11]: Shouldn't this script work regardless of database driver? Can this just be removed?

File: ping.py [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+
+engine = create_engine(url)
+print(f"Waiting for {url.host}:{url.port or 3306} to be ready")
+
+while True:
+    try:
+        engine.raw_connection().ping()
+        print()
```
Comment (ColdHeat) [inline ping.py:19]: I don't think this is necessary? Does it just mimic the original mysql client's behavior?

File: ping.py [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+        break
+    except:
```
Comment (ColdHeat) [inline ping.py:21]: Is there a more specific error that can be caught here?

**Review by ColdHeat — CHANGES_REQUESTED** [review]
I like the idea here! I think this is a good solution, just a few minor things that I think are worth addressing.

File: ping.py (hunk 2 above)
Comment (frankli0324) [reply ping.py:11]: `engine.raw_connection()` returns a underlying connection from another driver, `pymysql` in this case. `ping` is a mariadb/mysql only operation.

File: docker-entrypoint.sh (hunk 1 above)
Comment (frankli0324) [reply docker-entrypoint.sh:20]: but `config.py` does respects env variables...

File: ping.py (hunk 3 above)
Comment (frankli0324) [reply ping.py:19]: hmmm... no it doesn't. I agree this is weird, logging in to the database *then* sending a ping packet. does removing the `.ping()` part sound reasonable? by doing so we can also remove the `driver.startswith(mysql)` check

Comment (frankli0324) [reply ping.py:19]: how about

```python
while true try:
    engine.connect()
except pymysql.err.Error:
    ...
```

Comment (ColdHeat) [reply ping.py:19]: I just meant removing the empty `print` statement here actually but I will look into the `ping` method as well.

File: docker-entrypoint.sh (hunk 1 above)
Comment (ColdHeat) [reply docker-entrypoint.sh:20]: It respects the envvars but it won't fail the container if the secret key is being randomly generated. This check is primarily for having different secret keys across different workers.

File: ping.py (hunk 3 above)
Comment (ColdHeat) [reply ping.py:19]: Does this work though? I'm getting an error if MySQL isn't on. 

```
InternalError: (pymysql.err.InternalError) (1049, "Unknown database 'ctfd'")
(Background on this error at: http://sqlalche.me/e/2j85)
```

Comment (ColdHeat) [reply ping.py:19]: We do have SQLAlchemy-Utils so maybe you can use https://sqlalchemy-utils.readthedocs.io/en/latest/database_helpers.html?highlight=database_exists#sqlalchemy_utils.functions.database_exists?

Comment (ColdHeat) [reply ping.py:19]: It looks like you can do something like this: https://stackoverflow.com/a/17941078

Without a database then you can test for the raw connection.

Comment (ColdHeat) [reply ping.py:19]: Looks like this strategy would also work for postgres. 

So you would just need to take the url and recreate it without the database.

File: ping.py (hunk 4 above)
Comment (ColdHeat) [reply ping.py:21]: I'm okay with this being a catch all as long as this script is covered under flake8 and you ignore the flake8 lint.

File: ping.py (hunk 2 above)
Comment (ColdHeat) [reply ping.py:11]: With the strategy below you'd probably just want to exit if the driver is sqlite.

File: ping.py (hunk 3 above)
Comment (frankli0324) [reply ping.py:19]: I wrote that on my phone, haven't tested, sorry😓
it came to my mind that mariadb image actually created the database for us
image
so.... `database_exists` is fine I think?

Comment (ColdHeat) [reply ping.py:19]: You're right but `mysqladmin ping` only tests for connectivity to the database server. It doesn't check for existence of the database. It might be unnecessary but I would still rather let CTFd be responsible for creating the database if it doesn't exist. 

I think just creating a Python version of `mysqladmin ping` is the best way forward so we don't accidentally break something.

So just https://stackoverflow.com/a/17941078.

Comment (frankli0324) [reply ping.py:19]: I found that it's actually not that complicated

File: docker-entrypoint.sh (hunk 1 above)
Comment (frankli0324) [reply docker-entrypoint.sh:20]: I wrote the comments because my script actually imported `config.py`, so it's impossible for different workers to have different secret keys.

File: ping.py (hunk 3 above)
Comment (frankli0324) [reply ping.py:43]: the empty print statement is to print('ready') on a new line.

before:

```
Waiting for db: to be ready
..........db is ready
```

after:

```
Waiting for mysql+pymysql://ctfd:ctfd@db to be ready
.........
mysql+pymysql://ctfd:ctfd@db is ready
```

Comment (ColdHeat) [reply ping.py:43]: I don't really think it's necessary to have. Can you remove it?

File: docker-entrypoint.sh (hunk 1 above)
Comment (ColdHeat) [reply docker-entrypoint.sh:20]: I still think there are cases that could cause errors that are hard to debug. It's better to leave this as is. I doubt it causes any issues.

File: ping.py [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+        if url.drivername.startswith("mysql"):
+            mysql_ping(
+                host=url.host,
+                user=url.username,
+                password=url.password,
+                port=url.port,
+                database=None,
+            )
+        elif url.drivername.startswith("postgres"):
+            postgres_ping()
```
Comment (ColdHeat) [inline ping.py:42]: This is the wrong strategy to go with. You just need to do a `raw_connection()` on the URL without the database. Separating it out by postgres and mysql is unnecessary. You only really need to special case sqlite. For sqlite you can just `exit(0)`

Comment (frankli0324) [reply ping.py:42]: `raw_connection` for postgres doesn't support `ping`ing

Comment (ColdHeat) [reply ping.py:42]: I don't think you need to `ping()` specifically. `raw_connection()` in my testing worked only when the database was available for a connection. Otherwise it returned errors.

File: docker-entrypoint.sh [hunk 6]
```diff
@@ -6,8 +6,6 @@ WORKER_CLASS=${WORKER_CLASS:-gevent}
 ACCESS_LOG=${ACCESS_LOG:--}
 ERROR_LOG=${ERROR_LOG:--}
 WORKER_TEMP_DIR=${WORKER_TEMP_DIR:-/dev/shm}
-SECRET_KEY=${SECRET_KEY:-}
```
Comment (ColdHeat) [inline docker-entrypoint.sh:9]: This var change will also need to be reverted

File: ping.py (hunk 5 above)
Comment (frankli0324) [reply ping.py:42]: yes, it also checks if a database is created. this isn't what `mysqladmin ping` does.

Comment (ColdHeat) [reply ping.py:42]: mysqladmin ping just connects to the server. It doesn't test for database existence. 

https://serverfault.com/questions/32459/monitoring-what-does-mysqladmin-ping-report
https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html

Comment (ColdHeat) [reply ping.py:42]: raw_connection doesn't need a database specified, you just need to remove it from the URL.

Comment (frankli0324) [reply ping.py:42]: > mysqladmin ping just connects to the server. It doesn't test for database existence.
> 
> [serverfault.com/questions/32459/monitoring-what-does-mysqladmin-ping-report](https://serverfault.com/questions/32459/monitoring-what-does-mysqladmin-ping-report)
> [dev.mysql.com/doc/refman/8.0/en/mysqladmin.html](https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html)

I was trying to indicate the same thing... I wasn't aware that `raw_connection` accepts None as a database name...

Comment (frankli0324) [reply ping.py:42]: do you have some instant messaging app? it's is so inefficient making a discussion here......

**Comment by frankli0324** [comment]
running `make lint` locally doesn't produce any errors... wierd...

**Comment by ColdHeat** [comment]
I can review this locally and take over from here. Thanks for working on this!

**Review by ColdHeat — APPROVED** [review]
